---
name: D

"on":
  schedule:
    - cron: "0 0 1 * *" # run first day of every month
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        dc:
          - dmd-latest
          - ldc-latest
          - dmd-beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: 'Test'
        run: |
          dub test
